### ISSUE TITLE
[tasks] 各画面の整形

### ISSUE THREAD

**Issue by hiroakiashizawa** [hiroakiashizawa/ToDoList#23]
##  状態目標
- 各画面を整形して、初期デザイン案に近づける。
## TODO
- [x] 一覧画面(/tasks/index)
- [x] 完了画面(/tasks/complete)
- [x] 新規画面(/tasks/new)
- [x] 編集画面(/tasks/edit)
