### ISSUE TITLE
Viewの改善

### ISSUE THREAD

**Issue by hiroakiashizawa** [hiroakiashizawa/ToDoList#80]
##  状態目標
- 全体的なviewを見直す
## TODO
- [x] 共通レイアウト部分(layout/application.html.erb)見直し
- [x] 基本機能部分()/tasks,/tasks/users ..etc)見直し
- [x] 管理者コンソール(/tasks/admin)見直し
